#!/usr/bin/env python3


class Solution(object):
    def isPowerOfFour(self, num):
        """
        :type n: int
        :rtype: bool
        """
        if num <= 0:
            return False

        # power of four if only one bit is set in an odd bitpos
        if bin(num).count('1') == 1:
            if bin(num)[::-1].index('1') % 2 == 0:
                return True
        return False


if __name__ == '__main__':
    s = Solution()
    print(s.isPowerOfFour(16))
    print(s.isPowerOfFour(5))
    print(s.isPowerOfFour(512))
